version: '2'
networks:
  mired:
    ipam:
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1
services: 
  db:
    image: bitnami/mongodb:latest
    container_name: mongo_DB_examen
    networks:
     mired:
        ipv4_address: 172.29.0.11
    ports:
       - "27017:27017"
    expose:
     - 27017
  app-products:
    image: jalovi/productapp:1
    container_name: app_product_app_examen
    networks:
      mired:
        ipv4_address: 172.29.0.12
    expose:
      - 8080
    ports:
        - "8080:8080"
    depends_on:
      - db
